version: "3"
# networks:
#   mynet:
services:
  web_api:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web_api
    # networks:
    #   - mynet
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    links:
      - worker
    depends_on:
      - worker

# Redis
  redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
    # image: redis
    hostname: redis
    # networks:
    #   - mynet
    ports:
      - "6379:6379"

   # Celery worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile-celery
    volumes:
      - .:/app
    links:
      - redis
    depends_on:
      - redis
    # networks:
    #   - mynet
    command: ./run_celery.sh
